site_name: Alidade
site_url: https://keatonclark.github.io/alidade/
docs_dir: ./src

plugins:
  - fetch-files:
      paths: 
        - source: !ENV ALIDADE_HW
          destination: alidade-hw
  - search

extra_javascript:
  - https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js
  - javascripts/bom-table.js

theme:
  name: material
  palette:
    scheme: slate

extra:
  generator: false

extra_css:
  - https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css
  - stylesheets/gruvbox.css
  - stylesheets/tabulator.css


nav:
  - Home: index.md
  - Hardware:
    - Schematic: Schematic.md
    - Bom: Bom.md
    - Datasheets: Datasheets.md
    - Electrical Rules Checking: ERC.md
