site_name: Alidade
site_url: https://keatonclark.github.io/alidade/
docs_dir: ./src

plugins:
  - fetch-files:
      paths: 
        - source: !ENV ALIDADE_HW
          destination: alidade-hw

theme:
  name: material
  palette:
    scheme: slate

extra:
  generator: false

extra_css:
  - stylesheets/gruvbox.css


nav:
  - Home: index.md
  - Hardware:
    - Schematic: Schematic.md
    - Bom: Bom.md
    - Datasheets: Datasheets.md
    - Electrical Rules Checking: ERC.md
