name: Build Hardware

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Hardware Package
        run: nix build .#hw -L

      - name: Parse ERC Results
        run: python3 .github/scripts/parse_erc.py result/share/alidade/erc/alidade-erc.csv

      - name: Parse DRC Results
        run: python3 .github/scripts/parse_drc.py result/share/alidade/drc/alidade-drc.csv

      - name: Gather Outputs
        run: tar -czf alidade-hw-pkg.tar.gz -C result .

      - uses: actions/upload-artifact@v4
        with:
          name: alidade-hw-pkg
          path: alidade-hw-pkg.tar.gz
          retention-days: 7
