name: hw build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminantSystems/nix-installer-action@main
      - uses: DeterminantSystems/magic-nix-cache-action@main

      - name: build hw flake
        run: nix build .#hw

      - name: tar outputs
        run: tar --dereference --hard-dereference -czf outputs.tar.gz result*/

      - uses: actions/upload-artifacts@v4
        with:
          name: hw-outputs
          path: outputs.tar.gz
          retention-days: 7
      
